version: "3"
services:
  user-profile-service:
    build: user-profile-service/
    container_name: user-profile-service
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8083:8083
  payment-service:
    build: payment-service/
    container_name: payment-service
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 5000:5000



  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8761:8761
  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8080:8080
  product-webapp:
    build: product-webapp/
    image: product-webapp
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    container_name: product-webapp
    network_mode: host
    hostname: localhost
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"



